spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tus_assignment_auth?serverTimezone=UTC
    username: tus_db_user
    password: tus@123T89
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
    main:
      allow-bean-definition-overriding: true
  sql:
    init:
      mode: embedded
server:
  port: 8380
  error:
    include-message: always

hibernate:
  naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  defaultPassword: tus@123
